name: Deploy stuff
on:
  push:
  create:
    branches:
      - release_*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.com/lerna/lerna/issues/2542
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      - name: setup node
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
            registry-url: 'https://registry.npmjs.org'
      # https://github.com/lerna/lerna/issues/2542
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: npm install
      - run: npm run bootstrap
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm run publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Merge bump version commit
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${GITHUB_REF##*/}
          target_branch: ${GITHUB_REF##*/release_}
