name: Deploy

on:
  pull_request:
  branches: 
    - release_*
  types: [closed]

jobs:
  deploy:
    ## Only execute on merged PR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.com/lerna/lerna/issues/2542
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      - name: setup node
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
            registry-url: 'https://registry.npmjs.org'
      # https://github.com/lerna/lerna/issues/2542
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: npm install
      - run: npm run bootstrap
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: get published version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'lerna.json'
          prop_path: 'version'
      - run: git tag v${{steps.version.outputs.prop}} && git push --tags
